Create Member card
podcodar/webapp pull request #102
Opened 2021-12-23 16:33 UTC by wevertonvetim

# Descrição

Esta pull request implementa o card de membros

## Changes

- Criei o mock para simular os dados nescessários para a renderização do card 

It closes #76

2021-12-23 21:29 UTC, marco-souza requested changes
Bom Trabalho @wevertonvetim! 🎉

Eu sentido que os estilos tão meio "martelados", faltando um refinamento. Deixei alguns comentários que podem melhorar isso.

Em caso de duvidas recomendo dar uma lida nos seguintes links para afiar as ferramentas de estilo e layout:
- https://chakra-ui.com/docs/layout/grid
- https://chakra-ui.com/docs/layout/stack
- https://chakra-ui.com/docs/layout/flex

@Raysson-ornelas e @borgesgfj desbravaram o grid, se precisar de ajuda acho que eles podem ajudar

2021-12-23 21:29 UTC, marco-souza commented on packages/components/MemberCard.tsx
> +        maxW="14.75rem"
Não precisamos disso, quem define a largura é o grid/componente pai

2021-12-23 21:29 UTC, marco-souza commented on packages/components/MemberCard.tsx
> +        boxShadow="2xl"
to achando meio muito, que tal mudar apenas para `xl`?

2021-12-23 21:29 UTC, marco-souza commented on packages/components/MemberCard.tsx
> +          h="6.75rem"
não é um problema em si, mas ta um tamanho meio estranho 😅

será que rola de colocar um valor inteiro? 6 ou 7

2021-12-23 21:29 UTC, marco-souza commented on packages/components/MemberCard.tsx
> +          alt="memberPhoto"
o alt geralmente é um texto humanamente legibel, pois se a imagem falhar de carregar, o alt aparece.

Recomendo colocar algo como `"member cover"`

2021-12-23 21:29 UTC, marco-souza commented on packages/components/MemberCard.tsx
> +        <Flex justify="center" mt="-12">
ou, esse `mt` negativo não parece legal, será que conseguimos fazer isso de uma forma mais elegante no css?

2021-12-23 21:29 UTC, marco-souza commented on packages/components/MemberCard.tsx
> +            }}
```suggestion
            border="2px solid white"
```

2021-12-23 21:29 UTC, marco-souza commented on packages/components/MemberCard.tsx
> +            <Heading fontSize="2xl" fontWeight={500} fontFamily="body">
esse `fontFamily` não ta prestando não em. Existe essa font chamada `body`? Se não, é melhor remover

2021-12-23 21:29 UTC, marco-souza commented on packages/components/MemberCard.tsx
> +          <Stack direction="row" justify="center" spacing={5}>
Stack de stack não rola. Não seria melhor um grid aqui?

o Stack é um flexbox mais pesado, **sempre** que rolar de evitar ele é melhor. Não entendi bem a motivação dele, acho que um grid resolveria muito mais limpo

2021-12-23 21:29 UTC, marco-souza commented on packages/components/MemberCard.tsx
> +          <Box py={2} px={6}>
Não seria melhor só centralizar isso ao invés de ficar acertando tamanho de padding?

2021-12-23 21:29 UTC, marco-souza commented on pages/team.tsx
> +import Data from '@packages/utils/mocApi.json';
Variáveis e funções começam com letra minúscula.
Tipos e classes com a primeira letra maiúscula.

2021-12-23 21:29 UTC, marco-souza commented on pages/team.tsx
> +import MemberCardProfile from '@packages/components/MemberCard';
O nome do componente idealmente tem que bater com o nome do import. Melhor alterar o import
```suggestion
import MemberCard from '@packages/components/MemberCard';
```

2021-12-23 21:29 UTC, marco-souza commented on packages/components/MemberCard.tsx
> +          <Flex textAlign="center" direction="column">
Como todos os textos são centralzados, acho que vale a pena mover o `textAlign` para o `Box` pai

2021-12-26 14:43 UTC, fmagesty commented on packages/components/MemberCard.tsx
> +          alt="memberPhoto"
> 

 Pra uma pessoa cega por exemplo acho que se falar "PodCodar Member Photo" fica mais explicado

Mas no fim das contas essa pessoa vai ter acesso so ao alt e nunca ao conteudo da foto mesmo entao seria so pra ela saber o que esta naquela secao da pagina mesmo. Alt text eh uma coisa que se pa ta faltando nos componentes que fizemos no comeco do projeto, falando nisso

2021-12-26 14:50 UTC, frattezi commented on packages/utils/mocApi.json
> +{
Me parece que já temos a estrutura de "membros" criada no firestore, já não poderiamos fazer a ligação de uma vez e evitar crescer este mocApi local?

Isso levanta alguns pontos antes de fazer o merge:
- Poderiamos fazer uma leve adequação ao banco atual (wipe e adicionamos este dado)
- Existe uma forma de simular local o enviroment do firebase, poderiamos focar em evoluir este ferramental: https://firebase.google.com/docs/emulator-suite.


Meu comentário é mais uma observação, acredito que estou fora do projeto  e isso não me da visão de como está o ciclo de desenvolvimento de vocês ou plano futuro. ^^

2021-12-26 14:52 UTC, frattezi commented on pages/team.tsx
>    console.log(members, error);
na real já temos a estrutura aqui? Não valeria utilizar a fonte do firebase removendo o mock (e este log também =D)

2021-12-26 15:07 UTC, fmagesty commented on pages/team.tsx
> +          {users.map((user, id) => {
aqui eh so uma sugestao no nome da variavel. o user agora seria somente os membros entao faz sentido mas acho que se ao inves de user fosse member ficaria mais facil pra vc e outras pessoas baterem o olho e identificarem quem eh o user em questao. mas isso eh dboas, so achei relevante sugerir isso mesmo

ainda to lendo tudo no projeto pq to a muito tempo fora dele mas parece que ta ficando show demais mano, bom trabalho! 👍  

edit: isso aqui nao era pra fazer parte do review nao, fiz mer** mesmo haha

2021-12-26 15:11 UTC, frattezi reviewed
Parece que tem um conflitinho no file /team. Lembrar de resolver os conflitos antes do merge o/

2021-12-27 16:16 UTC, wevertonvetim commented on packages/components/MemberCard.tsx
> +        <Flex justify="center" mt="-12">
Em alinhamento ficou combinado que não haveria outra maneira de resover essa questão

2021-12-27 16:22 UTC, wevertonvetim commented on packages/utils/mocApi.json
> +{
As auterações no banco serão feitas em uma tarefa posterior, o objetivo dessa tarefa limita-se apenas ao componente visual, mas a evolução desta tela sera comsumir direto do banco de dados

2021-12-27 16:23 UTC, wevertonvetim commented on pages/team.tsx
>    console.log(members, error);
A estrutura do banco de dados e ainda não está de acordo a consumida pelo card, portanto haverá também uma tarefa para adequarmos esses dados

2021-12-27 17:51 UTC, marco-souza commented
A história de commits ta meio zoada, principalmente os ultimos. Tava bom, agora parece que piorou 😄 

Quando formos fazer `rebase`, o ideal é resolver o conflito no commit aonde ele ocorre, e não fazer um outro commit para resolver, isso é uma pratica muito ruim, acaba com a coesão na história de commit

2021-12-27 17:54 UTC, marco-souza commented on pages/team.tsx
>    console.log(members, error);
@frattezi  temos outra tarefa para isso, #89

2021-12-27 18:04 UTC, marco-souza requested changes
Estamos quase lá, so mais 4 alteraçoes

2021-12-29 00:51 UTC, marco-souza commented on packages/components/MemberCard.tsx
> +          <Box>
Repare bem que essa box é inutil, ela não adiciona nenhum estilo e nem serve para definir layout.

Acho que podemos removê-la.

2021-12-29 18:04 UTC, marco-souza approved these changes
Ship it! :shipit: 🚢

2021-12-29 18:08 UTC, merged