enh: add text to cta about podcodar's scholarships
podcodar/webapp pull request #119
Opened 2022-05-13 03:13 UTC by fmagesty

# Description

> Added some simple text in portuguese/english on the the call-to-action's description about donations and scholarships. Most importantly was to say that the community is free, so anyone who randomly stumbles on it don't mistake it for a paid service or at least know that PodCodar won't charge people to participate.

## Notes

> Was in doubt if I should write this PR in english or portuguese since it has been some time but checking other recent PRs it seems that english is the current pattern but please let me know otherwise.

Updated text in pt-br:
![image](https://user-images.githubusercontent.com/28074722/168203751-b5d4fc79-6da7-46e1-8091-804dcef640ce.png)

Updated text in english:
![image](https://user-images.githubusercontent.com/28074722/168203800-23bfb350-8529-42e2-9760-c44a54f914cf.png)

2022-05-16 00:10 UTC, marco-souza commented
Ou, to achando muita informaçao pra um bloco só. Talvez fosse melhor nas sessoes de baixo, de como funciona e tal

2022-05-18 00:10 UTC, vzsoares commented
só mencionando a issue ...
#104

2022-05-18 00:53 UTC, vzsoares commented
acho que o campo ideal para dizer que a podcodar é gratis é em `Nossa Metodologia` . e as informaçoes de bolsa creio q podem ficar junto no bloco de mentorias(MentoringSection) criando um novo CardItem `Sistema de bolsas` por exemplo

2022-05-18 00:54 UTC, vzsoares requested changes
acho que o campo ideal para dizer que a podcodar é gratis é em `Nossa Metodologia` . e as informaçoes de bolsa creio q podem ficar junto no bloco de mentorias(MentoringSection) criando um novo CardItem `Sistema de bolsas` por exemplo

2022-07-08 16:35 UTC, fmagesty commented
update: pessoal, desculpe mas acho que nao atualizei as mudancas sugeridas para este PR na data do mesmo. vou revisar aqui e conferir se ja nao foi implementado no codigo atual mas se nao ja as faço agora e atualizo aqui. tava ate pegando poeira ja esse PR kkk

2022-07-08 18:42 UTC, fmagesty commented
> Ou, to achando muita informaçao pra um bloco só. Talvez fosse melhor nas sessoes de baixo, de como funciona e tal

vendo aqui novamente apos alguns meses eu achei muito texto pra um bloco tambem. ainda mais no comecinho da pagina. to pensando em nem colocar isso la mais mesmo ate ter um lugarzin bom. mas ainda acho importante o pessoal novo saber disso de alguma forma tambem porque eu sei o tanto q isso foi importante quando eu tava começando so lendo recurso de graça na internet ai o fato disso tudo aqui nunca ter me cobrado dinheiros foi muito importante tambem. apesar q no meu caso e na maioria do pessoal a gente ainda tem um canal direto com algum membro ai essa questao fica mais pro boca-a-boca mesmo. enfim, se a podcodar crescer (e eu acredito q cresce :3) o fato de deixar transparente a questao de ensino gratis e possibilidade de doaçoes se torna cada vez mais importante, na minha opiniao. e agora como ja foi mencionado na ultima reuniao sobre a podcodar querer que neste ciclo seja aumentado o numero de doacoes eu acho que ter isso claro no webapp iria complementar as parcerias quando algum membro mostrar o site para parceiros em potencial. textao mas eh isso ai

> acho que o campo ideal para dizer que a podcodar é gratis é em `Nossa Metodologia` . e as informaçoes de bolsa creio q podem ficar junto no bloco de mentorias(MentoringSection) criando um novo CardItem `Sistema de bolsas` por exemplo

hmm, to lendo aqui de novo e na real eu nao acho que a metodologia seria o melhor lugar, ainda. inclusive to me questionando se  o titulo 'nossa metodologia' esta correto em primeiro lugar. nesse caso eh so picuinha ja que da pra entender do mesmo jeito mas vcs nao acham que no lugar de 'metodologia' faria mais sentido usar a palavra metodo? aqui a definicao de ambos q achei no google rapidim agora:

metodologia: 
<img width="887" alt="image" src="https://user-images.githubusercontent.com/28074722/178051774-2b16312b-5132-4356-b2db-87f56eceabc9.png">

metodo:
<img width="889" alt="image" src="https://user-images.githubusercontent.com/28074722/178051825-28081309-8ec9-41b6-82ac-4a1bf880ac02.png">

2022-07-08 18:43 UTC, fmagesty commented
> 

essa

>  e as informaçoes de bolsa creio q podem ficar junto no bloco de mentorias(MentoringSection) criando um novo CardItem `Sistema de bolsas` por exemplo

opa, mas isso aqui eh interessante, hein. acho uma boa

2022-09-01 21:58 UTC, closed without merging