Feat/add howitworkssection
podcodar/webapp pull request #22
Opened 2021-08-24 20:54 UTC by fmagesty

# Descrição

> Adiciona secao na pagina home que contem uma breve descricao de como funcionam os processos da PodCodar

## Changes

> Muita coisa mudou, incluindo:
-Componentizacao: Secoes que utilizavam Box, Icon, Heading e Text, nesta ordem, foram condensadas dentro de um componente que usa js para mapear seu conteudo de icone, heading e texto
- Todos os valores antes utilizados em unidades de px foram mudados para seus respectivos valores em rem
- O uso do react icon foi removido e estamos somente utilizando o chrakra icons e imagens svg
- Varias outras mudancas

## Notes

> Deixem seus comentarios se acharem algo interessante de ser falado

2021-08-24 20:56 UTC, fmagesty commented
ps: sei que tem muito commit ai galera, foi mal mas to ajustando com esse processo todo ainda. Tambem acho que rolou uns commits desnecessarios na hora do rebase

2021-08-25 12:22 UTC, frattezi commented on pages/index.tsx
> +import HowitWorksSection from '@packages/components/HowItWorksSection';
O padrão camelCase está incorreto, ctrl + C -> ctrl + v

2021-08-25 12:22 UTC, frattezi commented on pages/index.tsx
> +          <HowitWorksSection />
Aqui também

2021-08-25 12:27 UTC, marco-souza commented
Não revisei ainda, mas essa quantidade de commit com nome genérico não ta bom. Recomendo ou resolver a historia commit por commit ou criar uma nova branch reaproveitar apenas os arquivos quando tiverem prontos para serem mergeados

2021-08-25 12:30 UTC, frattezi reviewed
Alou melg, cara não podemos aceitar uma história de commits confusa e sem sentido sendo mergeada na nossa aplicação concorda? Logo não entendo e vou desconsiderar seu comment, e espero que faça as correções ou via git, ou recriando a sua branch e refazendo os commits do zero (eu sugiro essa opção).

Se precisar de ajuda pode me procurar, por favor!

2021-08-25 12:30 UTC, frattezi commented on yarn.lock
> +<<<<<<< HEAD
Aqui são erros de conflito, veja bem, conflitos de GIT

Eu e o @marco-souza falamos algumas vezes sobre, deletar este arquivo após as ações no git e regerá-lo utilizando o comando `yarn`.

Ter errors em um arquivo auto-gerado não pode, ainda mais depois de ter sido avisado (╯°□°)╯︵ ┻━┻

2021-08-25 12:30 UTC, frattezi commented on packages/components/HowItWorksSection.tsx
> +  const ColumnSection = () => {
const
const 
const?

Essa lógica precisa ser colocada toda dentro do componente dessa forma? Lembre-se que falamos sobre deixar os compoenentes Secos, com a lógica por fora em funções bem encapsuladas.

2021-08-25 12:30 UTC, frattezi commented on packages/components/HowItWorksSection.tsx
> +        {content &&
Content é declarado por você, por que a lógica de &&

2021-08-25 13:02 UTC, marco-souza commented
Mano, cadê os comentários antigos?

2021-08-25 13:05 UTC, marco-souza requested changes
Precisamos pensar mais antes de bater código, não temos pressa de entregar as cosias aqui, o objetivo é estudar e aprender.

Recomendo:
- quebrar em pequenos passos antes de começar (adicionar page, criar component, add icons, etc)
  - fazer (idealmente) um commit para cada mudança planejada previamente
  - evitar commits com nomes genéricos
- pensar seu componente com o mínimo de lógica possível
- Utilizar props com mais fluencia
- Pensar em como você espera que seu componente seja usado

O primeiro primeiro revisor é quem desenvolve. Recomendo sempre revisar seu PR antes de marcar outras pessoas para review.

2021-08-25 15:55 UTC, closed without merging