Adiciona secao WhyItWorks, substituindo a antiga HowItWorks com novos icones
podcodar/webapp pull request #27
Opened 2021-08-30 15:31 UTC by fmagesty

# Descrição

- A antiga secao HowItWorks foi totalmente refeita como WhyItWorks, explicando por que a PodCodar funciona.

## Changes

- Os textos foram enxugados e adaptados para a nova secao
- Feitas correcoes de estilo
- Novos icones adicionados

## Notes

- Importante notar que o import de novos icones foi feito normalmente como estavamos fazendo ate entao, porem como o arquivo chegou num ponto de ficar extenso demais, criei uma tarefa que ira refatorar estes icones para dentro de uma pasta separada, como pode ser visto na [tarefa da board](https://podcodar.notion.site/Refatorar-o-componente-Icons-tsx-em-uma-pasta-separada-6465d94e8b9f4f688ee518185e0dd201)

2021-08-30 16:32 UTC, marco-souza requested changes
Mano, acho que vc esqueceu do rebase, tentei fazer aqui e deu alguns conflitos. Lembre de dar rebase sempre antes de abrir uma PR.

Além disso, tem muito commit pra pouca coisa. Acho que podemos melhorar isso. Bora fazer outra PR com os commits certinhos?

Sobre os nomes dos commits, também vale lembrar: 
- fea: funcionalidade nova
- enh: melhorar em algo que ja existe


No mais, deixei alguns comments relativo aos styles.

2021-08-30 16:32 UTC, marco-souza commented on packages/components/WhyItWorksSection.tsx
> +      <Text color="gray.500" marginTop="1rem" maxWidth="30rem">
Acho que podemos tirar o `maxWidth` e deixar a margin no `Heading`.

```suggestion
      <Text color="gray.500" >
```

2021-08-30 16:32 UTC, marco-souza commented on packages/components/WhyItWorksSection.tsx
> +      <Heading size="md" fontWeight={400} pb="1rem">
```suggestion
      <Heading size="md" fontWeight={400} mb="2rem">
```

2021-08-30 17:38 UTC, fmagesty commented
> Mano, acho que vc esqueceu do rebase, tentei fazer aqui e deu alguns conflitos. Lembre de dar rebase sempre antes de abrir uma PR.
> 
> Além disso, tem muito commit pra pouca coisa. Acho que podemos melhorar isso. Bora fazer outra PR com os commits certinhos?
> 
> Sobre os nomes dos commits, também vale lembrar:
> 
> * fea: funcionalidade nova
> * enh: melhorar em algo que ja existe
> 
> No mais, deixei alguns comments relativo aos styles.

mano q estranho. eu dei rebase agorinha e tinha so o whyitworks como mudanca
agora ta assim: PS C:\Users\Felipe\Desktop\webapp> git rebase main
Current branch feat/section-whyitworks is up to date.

espero q tenha sido resolvido entao

2021-08-30 18:18 UTC, marco-souza commented
Pelo seus commits vc deu foi merge ai, ola o seus commits

2021-08-30 18:18 UTC, marco-souza commented
Acho que a historia de commit ta bem fora já. 13 commits pra alterar 3 arquivos parece errado sabe

2021-08-31 13:15 UTC, marco-souza commented
Outro ponto também é que as colunas não estão com larguras iguais
![image](https://user-images.githubusercontent.com/4452113/131508965-02bcff7b-3fc2-4ce4-ab4e-bc2689ba0c87.png)

2021-08-31 13:21 UTC, fmagesty commented
> Outro ponto também é que as colunas não estão com larguras iguais
> ![image](https://user-images.githubusercontent.com/4452113/131508965-02bcff7b-3fc2-4ce4-ab4e-bc2689ba0c87.png)

boa, eu reparei nisso ontem tb mas tava cansado e n lembrei de arrumar. to mexendo nisso agora

2021-08-31 13:50 UTC, fmagesty commented
![image](https://user-images.githubusercontent.com/28074722/131513710-f8013750-3679-4b69-ad37-f4a9bcb2eece.png)
@marco-souza 
Entao, qq pega: ali eh um stack pai dos CardItems que por sua vez tem um elemento box (na cor azul) wrapping o card. 
Cada espaco ali nao eh da coluna em si, eh o gap entre elas. tambem tinha achado estranho qnd inspecionei mas fui ver mais a fundo e eh isso q ta rolando.

Nesse exemplo eh possivel ver o mesmo espaco entre cada card/box na versao mobile:
![image](https://user-images.githubusercontent.com/28074722/131514226-08ab35c4-07cc-49cf-9222-5a4fc3f2ea8e.png)

Entao elas vao ter essa margin mesmo. Eu creio que eh pra ser assim mesmo mas da ideia se nao for. 

ps: to mexendo na outra branch, conforme a gente discutiu, pra acertar os commits

2021-08-31 14:07 UTC, closed without merging