fea: create team page route
podcodar/webapp pull request #79
Opened 2021-11-24 22:19 UTC by borgesgfj

- create `/team` route
- insert  Heading componente
- create page title
- translate title

# Descrição
 Create a team page with a route to `/team` and configure the page tilte in pt-br and english. 

## Changes
- create a `/team` route in `/pages` directory;
- Add a Section component in `/pages/team` with a Heading component to page title;
- Add a `team-page` section in /packages/locale/en.yml and /packages/locale/pt.yml with a title key.

2021-11-24 23:00 UTC, marco-souza requested changes
Muito bom trabalho!

Requisitei algumas alterações para manter as boas práticas do projeto. Fique à vontade para puxar uma discussão ou levantar uma duvida!  🚀

2021-11-24 23:00 UTC, marco-souza commented on packages/features/i18n-context.tsx
> +  | 'team-page';
bem lembrado 👍🏼

2021-11-24 23:00 UTC, marco-souza commented on pages/team.tsx
> +      <Stack textAlign="center" align="center" spacing={{ base: 8, md: 10 }}>
Me parece que esse stack está cumprindo o papel de um `Flex`, pois, como só temos um item, o spacing não faz diferença, seria o mesmo que usar um `margin-bottom`. 

Vamos evitar usar stack sem necessidade. Recomendo passar ele pra Flex, para ser mais explicito.

2021-11-24 23:00 UTC, marco-souza commented on pages/team.tsx
> +import Section from '../packages/components/Section';
Vamos evitar importes relativos (`..`). Temos configuraçoes para facilitar isso:
```suggestion
import Section from '@packages/components/Section';
```

2021-11-24 23:00 UTC, marco-souza commented on pages/team.tsx
> +              span: <Text as="span" color="purple.400" />,
Maneiro 👍🏼

2021-11-24 23:00 UTC, marco-souza commented on pages/team.tsx
> +function Team() {
Note que criamos a função aqui, porém só saberei que ela é o `export default` no final do arquivo. 
Isso não é uma boa pratica, pois quebra no fluxo de leitura.

Imagino que isso seja gerado por um atalho no vscode, mas existe um outro (`rfc` se não me engano) que faz isso corretamente.

Recomendo colocar o `export default` aqui e remover a ultima linha por questões de legibilidade

2021-11-25 13:17 UTC, borgesgfj commented on pages/team.tsx
> +      <Stack textAlign="center" align="center" spacing={{ base: 8, md: 10 }}>
Ah boa. Vou alterar aqui!

2021-11-25 13:18 UTC, borgesgfj commented on pages/team.tsx
> +import Section from '../packages/components/Section';
O `@` então já faz referência para a raiz?

2021-11-25 13:18 UTC, borgesgfj commented on pages/team.tsx
> +function Team() {
Ah blz!

2021-11-25 14:47 UTC, marco-souza approved these changes
Ship it! 🚢

2021-11-25 14:49 UTC, merged