Fea/insert social icons to footer
podcodar/webapp pull request #80
Opened 2021-11-26 22:45 UTC by Filipe-barbosa

# Descrição

-Create component for use social-buttons
- insert logo to footer. 
-  modify background color to footer
-  insert logo to footer

![image](https://user-images.githubusercontent.com/65319425/143659569-6e45058b-4684-4c80-a416-218108d72b37.png)

2021-11-29 11:16 UTC, Filipe-barbosa commented on packages/components/Footer.tsx
> +      <Logo size="large" />
Dentro das medidas padrões estabelecidas no template, este é o tamando máximo que consigo chegar com a imagem. Mas posso olhar sim a respeito pra ver o que consigo fazer

2021-11-29 12:34 UTC, marco-souza commented on packages/components/Footer.tsx
> +      <Logo size="large" />
deve ter um `xlarge`

2021-11-29 13:00 UTC, marco-souza requested changes
Boa refatoração! 👏 

Acho que algumas coisas passaram batidas, principalmente na questão de organização e estilo de código. Alguns pontos que valem destaque:

1. Sei que alguns errors já estava ai quando vc chegou, mas nossa obrigação como dev é, sempre que alterar um código, deixar ele melhor do que era antes.
2. Esse código foi formatado e lintado? Parece que muitas coisas não foram resolvidar pelo prettier e nem eslint barrou. Se for mesmo o caso de não funcionar, precisamos de outra tarefa para resolver isso. não rola ficar revisando espaço faltando entre funções
3. Nome da PR está novamente fora do padrão

2021-11-29 13:26 UTC, marco-souza commented
Cara, outra coisa é o nome da PR, ta sempre vindo errado. Vamos lembrar de editar par ser also assim

```
FEA: Add team page
ENH: refactoring footer
OTH: update dependencies
```

2021-11-29 23:21 UTC, Filipe-barbosa commented on packages/components/Footer.tsx
> +      <Logo size="large" />
A diferença do x large pro large da mais que o dobro do tamanho o que cresce ainda mais o footer, a meu ver ficando estranho.

2021-12-01 01:57 UTC, Filipe-barbosa commented on packages/components/Footer.tsx
> +    <Stack spacing="0.1rem" flex="0.3" alignItems="center" textColor="gray.50">
As cores funcionam bem no darck Team 
![image](https://user-images.githubusercontent.com/65319425/144157850-8aec3198-58ae-45f4-b3a0-6172f000fe50.png)

2021-12-01 01:58 UTC, Filipe-barbosa commented on packages/components/Footer.tsx
> +    <Stack spacing="1rem" flex="0.5" alignItems="center" color="gray.50">
a cor funciona passada para o pai e foi aplicado

2021-12-01 10:46 UTC, marco-souza commented on packages/components/Footer.tsx
> +  const { t } = useI18n('footer');
Isso ainda não foi resolvido

2021-12-01 10:46 UTC, marco-souza commented on packages/components/Footer.tsx
> +    <Stack alignItems="center">
Todos os 3 items tem alignItem, será que poderia ser passado para o pai tbm?

2021-12-01 10:46 UTC, marco-souza commented on packages/components/Footer.tsx
> +      <HStack spacing="1rem" justifyContent="center" fontSize="1.3rem">
Move esse stack pros icones, ao inves de deixar eles só com o fragment

2021-12-01 10:46 UTC, marco-souza commented on packages/components/Metadata.tsx
> -import {
Pq isso mudou? Vamos evitar mudar arquivos que não estão relacionados a mudança do PR

2021-12-01 10:46 UTC, marco-souza commented on packages/components/Footer.tsx
> +      <HStack spacing="1rem" justifyContent="center" fontSize="1.3rem">
Fica meio estranho fazer um componente que precisa ser acomapnhado de outro (no caso o hstack)

2021-12-01 10:53 UTC, marco-souza commented on packages/components/Metadata.tsx
> -import {
Ah sim isso foi o `yarn fmt`, vamos deixar essas mudanças ai por enquanto, mas nas próximas é bom ficar ligado nisso. Temos que ver se o fmt ta rodando normal na hora do commit

2021-12-01 18:13 UTC, Raysson-ornelas approved these changes

2021-12-06 23:11 UTC, marco-souza commented on packages/components/Footer.tsx
> +      <HStack spacing="1rem" justifyContent="center" fontSize="1.3rem">
Fiz um commit alterando isso

2021-12-06 23:18 UTC, marco-souza commented on packages/components/Footer.tsx
> +    <Stack alignItems="center">
Fiz um css personalizado para resolver isso

2021-12-06 23:23 UTC, marco-souza approved these changes

2021-12-07 10:51 UTC, merged